travis:
  secure:
    BINSTAR_TOKEN: wE8VrG1xhal08+VuV+L8rwvhuPmDMs+fmnuaV664Cuq1yNVSrucSJuZhQCjMUC3FhXsC4yrkBvZzf35AwshRWLQjjYbRcziqK8m3KauWrNBumWXCLGzXtMafR8E4vvarIyzYOXCW2hj69TGyZX/fsnafcntnKM2I6nC4j1E9tvvYpcIzclhoZ+pCvUtdnh+swGxVZJhAcSVqxCp+li/FKkRZJQczg1de0c/rZTfEPTswLSTe/8/wnbJsaj513uy6PGoMbpN47MAqkQH+H7TyPo4eL3q+sSJsnvLHiDB29KMtGsf8auJp4Hnp+za+W1DQS0rANu57hz/SlmbmxoEW3sxWD7gcKuU1/DngsJTshjtF257YrHFAjvB1g/ey3lm27x3yDSqgldSKewzeSCikZAL0AYM8og0jxFvIWY4l8xl1yoeEIO61Xy1TNyv3DovIFGVIFroVXWVP8RurKw2wH6DENG13RIGpzkz+2slyVYobSTZoKuNAOanAP8sp59tg+JMLhf4Juj0fJaUWU/7FFyEsQP0wL/EktHnftUULCDUFg5jum7SWtleD7sM9d1lycIBKMmUxRPjSHzqPo9szYZU27qwZqt2TIyJlyIvj/4yJELVuTrrt+hZvFLAQwJRw8ZX98sd8a+qTcgmcnHfCUETEXsQ8B3xAi+zDML08XsQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
